// Stuff assumed to be in main:
 public enum Gender {
 GENDER_MALE, GENDER_FEMALE, GENDER_UNDEFINED
 }

 public enum Ai {
 AI_DEFAULT, AI_RECKLESS, AI_CAUTIOUS
 }

 public enum Role {
 ROLE_FIGHTER, ROLE_ROGUE, ROLE_PALADIN, ROLE_WIZARD, ROLE_HEALER, ROLE_BARD, ROLE_ADVENTURER
 }

 public enum EquipSlot {
 SLOT_NONE, SLOT_HEAD, SLOT_BODY, SLOT_HANDS, SLOT_LEGS, SLOT_FEET, SLOT_WEAPON, SLOT_OTHER
 }

 public enum ObjectType {
 OBJECT_EQUIPMENT, OBJECT_HEALTHPOTION, OBJECT_MANAPOTION, OBJECT_BOTHPOTION, OBJECT_KEY, OBJECT_OTHER
 }

 void output(String outtext){
 // do output stuff here
 }
